meta_product_name: "Pandemic Volunteers"
meta_title: "Pandemic Volunteers – You can save lives!"
meta_description: "Let us help tackling the coronavirus pandemic with fewer deaths."
meta_image: "opengraph/image.png"
twitter_account: "@PandemicVolntrs"